Develop
shloch/Bubble_sort_RUBY pull request #1
Opened 2019-04-02 17:21 UTC by shloch

2019-04-03 00:37 UTC, zlayabekrija requested changes
Excellent work, please fix these minor things and I would like to suggest to implement this sorting algorithm in Enumerable method.
Please resubmit the new review request.
Happy coding. 😄

2019-04-03 00:37 UTC, zlayabekrija commented on bubble_sort.rb
> +    puts arr
please remove puts from code

2019-04-03 00:37 UTC, zlayabekrija commented on bubble_sort.rb
> +    print arr.to_s + "\n"
Please remove print,puts or p from code.

2019-04-03 00:37 UTC, zlayabekrija commented on bubble_sort.rb
> +            var = yield arr[i], arr[i+1]
what if I forget to provide you with a block. Please take this into consideration.

2019-04-03 13:57 UTC, shloch commented
Thanks for the review.....i submitted proposed solution

2019-04-03 18:11 UTC, zlayabekrija requested changes
You are one line from completing please follow up, with suggestion and resubmit review request.
Happy coding. 😄

2019-04-03 18:11 UTC, zlayabekrija commented on bubble_sort.rb
> +            var = yield arr[i], arr[i+1]
before checking for yield, first check if there is any block given

2019-04-06 23:15 UTC, zlayabekrija requested changes
Please fix the commented line, and resubmit review request.
Happy coding.

2019-04-06 23:15 UTC, zlayabekrija commented on bubble_sort.rb
> +                "no block"
I the case without a block, you should do the same as in regular bubble sort, sort it in order.
` if arr[i] > arr[i+1]
                arr[i+1], arr[i] = arr[i], arr[i+1]
end `, and with this you have cover both scenarions in bubble_sort_by

2019-04-08 10:22 UTC, shloch commented on bubble_sort.rb
> +                "no block"
thanks for your reviews

i added the corrections

2019-04-08 17:28 UTC, zlayabekrija approved these changes
Great work, good luck with the next projects. Thumbs up 👍  Happy Coding.

2019-04-09 17:12 UTC, merged